using UnityEngine;

/// <summary>
/// All possible modification points where talents can inject functionality
/// </summary>
public enum ModifierType
{
    // Health System
    BEFORE_HEALING,
    AFTER_HEALING,
    BEFORE_DAMAGE_TAKEN,
    AFTER_DAMAGE_TAKEN,
    MODIFY_HEALTH_AMOUNT,
    MODIFY_MAX_HEALTH,
    ON_LOW_HEALTH_TRIGGER,
    BEFORE_DEATH,
    ON_DEATH,

    // Shield System
    SHIELD_RECHARGE_RATE,
    SHIELD_RECHARGE_DELAY,
    BEFORE_SHIELD_DAMAGE,
    AFTER_SHIELD_DAMAGE,
    DAMAGE_TYPE_SHIELD_MODIFIER,
    ON_SHIELD_DEPLETED,
    MODIFY_SHIELD_AMOUNT,
    MODIFY_MAX_SHIELD,

    // Damage System
    BEFORE_DAMAGE_HANDLER,
    BEFORE_DEFENSE_CALCULATION,
    AFTER_DEFENSE_CALCULATION,
    BEFORE_HEALTH_DAMAGE,
    AFTER_DAMAGE_DEALT,
    BEFORE_CRIT_CALCULATION,
    AFTER_CRIT_CALCULATION,
    ON_CRITICAL_HIT,

    // Weapon System
    BEFORE_WEAPON_FIRING,
    ON_WEAPON_STOP_FIRING,
    PRE_WEAPON_FIRE,
    AFTER_WEAPON_FIRE,
    WEAPON_DAMAGE_MODIFIER,
    PROJECTILE_VELOCITY_MODIFIER,
    AUTO_FIRE_RATE_MODIFIER,
    ABILITY_COOLDOWN_CHECK,
    ABILITY_COOLDOWN_MODIFIER,
    BEFORE_WEAPON_ABILITY,
    AFTER_WEAPON_ABILITY,
    BEFORE_PROJECTILE_CREATION,

    // Movement System
    BEFORE_MOVEMENT_CALCULATION,
    AFTER_MOVEMENT_CALCULATION,
    MOVEMENT_ACCELERATION_MODIFIER,
    MOVEMENT_DECELERATION_MODIFIER,
    BEFORE_ROTATION_CALCULATION,
    ROTATION_SPEED_MODIFIER,
    REGISTER_MOVEMENT_MODIFIER,
    UNREGISTER_MOVEMENT_MODIFIER
}
